name: jumpit_boilerplate
description: jumpit app architecture

publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # section: architecture component
  arc:
    git: https://github.com/akthfdyd/arc.git
  #    path: ../arc
  get_it: ^7.2.0

  # section: network
  http: ^0.13.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - mockdata/